name: reports and artifacts

on:
  push:
    branches:
      - gh-reports
  pull_request:
    branches:
      - gh-reports

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      reports-file: ${{steps.publish.outputs.dummy-file}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    -  name: Publish html file name
       id: publish
       run: find reports/*.html -type f -execdir echo '{dummy-file={}}' >> $GITHUB_OUTPUT ';'
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: reports-file
        path: reports
        #path: |
        #  reports
        #  dummy-file.html
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3     
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with: 
        name: reports-file
    - name: Display content
      run: ls
    - name: Output file name
      run: echo "${{needs.test.output.reports-file}}"

