name: Java CI

on:
  push:
    branches:
      - gh-custom-action

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: My First Custom Action
        id: welcome
        uses: ./.github/actions/ctest
        with:
          message: 'welcome to my third github custom action'

      - name: Print Welcome Message
        run: echo "The message printed by the custom action is: ${{ steps.welcome.outputs.printed-message }}"

      - name: Build and test
        run: |
          mvn clean install
          mvn test

  Deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Deploy
        run: echo "deploying microservice application"

