name: reports and artifacts

on:
  push:
    branches:
      - gh-reports
  pull_request:
    branches:
      - gh-reports

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: reports-file
        path: reports
        #path: |
        #  reports
        #  dummy-file.html
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3     
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with: 
        name: reports-file
    - name: Display content
      run: ls

