name: Java CI

on:
  push:
    branches:
      - gh-executionflow
  pull_request:
    branches:
      - gh-executionflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build and test
      id: bandt
      run: |
        mvn clean install
        mvn test
    - name: Publish test reports
      if: steps.bandt.report == 'failure'
      run: echo "...Test result failed..."
        
  Deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Deploy
      run: echo "deploying microservice application"

  Reports:
    needs: [test, Deploy]
    if: failure()
    runs-on: ubuntu-latest
    
    steps:
    -  name: validation steps
       run: echo "validate if conditions"

